// RTK frames for every kanji used in ./mock, copied from rtk-api's GET /frames
// so the mock page makes no API calls. A kanji missing from this map is
// treated as outside RTK.
export const KANJI: Record<string, { frame: number; keyword: string }> = {
  日: { frame: 12, keyword: 'day' },
  古: { frame: 16, keyword: 'old' },
  占: { frame: 49, keyword: 'fortune-telling' },
  卓: { frame: 52, keyword: 'eminent' },
  朝: { frame: 53, keyword: 'morning' },
  子: { frame: 99, keyword: 'child' },
  母: { frame: 105, keyword: 'mama' },
  大: { frame: 112, keyword: 'large' },
  理: { frame: 283, keyword: 'logic' },
  輝: { frame: 324, keyword: 'radiance' },
  京: { frame: 334, keyword: 'capital' },
  週: { frame: 340, keyword: 'week' },
  言: { frame: 357, keyword: 'say' },
  計: { frame: 359, keyword: 'plot' },
  調: { frame: 373, keyword: 'tune' },
  載: { frame: 383, keyword: 'load' },
  政: { frame: 407, keyword: 'politics' },
  越: { frame: 413, keyword: 'surpass' },
  哀: { frame: 428, keyword: 'pathetic' },
  風: { frame: 563, keyword: 'wind' },
  記: { frame: 568, keyword: 'scribe' },
  家: { frame: 580, keyword: 'house' },
  達: { frame: 591, keyword: 'accomplished' },
  庁: { frame: 635, keyword: 'government office' },
  持: { frame: 712, keyword: 'hold' },
  揮: { frame: 715, keyword: 'brandish' },
  才: { frame: 736, keyword: 'genius' },
  友: { frame: 760, keyword: 'friend' },
  台: { frame: 805, keyword: 'pedestal' },
  会: { frame: 814, keyword: 'meeting' },
  置: { frame: 895, keyword: 'placement' },
  従: { frame: 942, keyword: 'accompany' },
  彼: { frame: 948, keyword: 'he' },
  徹: { frame: 951, keyword: 'penetrate' },
  徴: { frame: 952, keyword: 'indications' },
  微: { frame: 954, keyword: 'delicate' },
  私: { frame: 968, keyword: 'private' },
  住: { frame: 1027, keyword: 'dwell (live)' },
  休: { frame: 1038, keyword: 'rest' },
  信: { frame: 1043, keyword: 'faith' },
  府: { frame: 1077, keyword: 'municipality' },
  座: { frame: 1100, keyword: 'sit' },
  幣: { frame: 1118, keyword: 'cash' },
  蔽: { frame: 1119, keyword: 'cover over' },
  弊: { frame: 1120, keyword: 'abuse' },
  遊: { frame: 1126, keyword: 'play' },
  社: { frame: 1173, keyword: 'company' },
  宗: { frame: 1181, keyword: 'religion' },
  崇: { frame: 1182, keyword: 'adore' },
  所: { frame: 1208, keyword: 'place' },
  事: { frame: 1240, keyword: 'matter' },
  画: { frame: 1254, keyword: 'brush-stroke' },
  師: { frame: 1361, keyword: 'expert' },
  過: { frame: 1389, keyword: 'overdo' },
  阪: { frame: 1390, keyword: 'Heights' },
  隣: { frame: 1408, keyword: 'neighboring' },
  食: { frame: 1582, keyword: 'eat' },
  新: { frame: 1619, keyword: 'new' },
  表: { frame: 1666, keyword: 'surface' },
  星: { frame: 1676, keyword: 'star' },
  睡: { frame: 1707, keyword: 'drowsy' },
  今: { frame: 1711, keyword: 'now' },
  開: { frame: 1750, keyword: 'open' },
  聞: { frame: 1754, keyword: 'hear' },
  喉: { frame: 1768, keyword: 'throat' },
  痛: { frame: 1825, keyword: 'pain' },
  発: { frame: 1840, keyword: 'discharge' },
  療: { frame: 1845, keyword: 'heal' },
  無: { frame: 1913, keyword: 'nothingness' },
  悪: { frame: 1951, keyword: 'bad' },
  眠: { frame: 1977, keyword: 'sleep' },
  都: { frame: 1989, keyword: 'metropolis' },
  来: { frame: 2029, keyword: 'come' },
  衰: { frame: 2037, keyword: 'decline' },
  衷: { frame: 2038, keyword: 'inmost' },
  邪: { frame: 2055, keyword: 'wicked' },
  喪: { frame: 2076, keyword: 'miss' },
  駅: { frame: 2138, keyword: 'station' },
  能: { frame: 2160, keyword: 'ability' },
};
